import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { ArrowLeft, FileText, Scale, AlertTriangle, Shield, CreditCard, Users, Globe } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import Footer from "@/components/Footer";

const TermsOfService = () => {
    const navigate = useNavigate();

    return (
        <div className="min-h-screen bg-gradient-to-br from-background via-background/95 to-primary/5">
            {/* Background Pattern */}
            <div className="absolute inset-0 opacity-40">
                <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-accent/5" />
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_1px_1px,rgba(156,146,172,0.15)_1px,transparent_0)] bg-[length:20px_20px]" />
            </div>

            <div className="relative">
                {/* Header */}
                <div className="bg-background/95 backdrop-blur-md border-b border-border/20 sticky top-0 z-50">
                    <div className="container mx-auto px-4 py-4">
                        <div className="flex items-center justify-between">
                            <div className="flex items-center space-x-4">
                                <Button
                                    variant="ghost"
                                    size="sm"
                                    onClick={() => navigate(-1)}
                                    className="text-foreground-muted hover:text-foreground"
                                >
                                    <ArrowLeft className="w-4 h-4 mr-2" />
                                    Back
                                </Button>
                                <div className="h-6 w-px bg-border" />
                                <h1 className="text-xl font-bold">Terms of Service</h1>
                            </div>
                            <Link to="/" className="text-lg font-bold text-primary">
                                Cinesaga
                            </Link>
                        </div>
                    </div>
                </div>

                {/* Content */}
                <div className="container mx-auto px-3 sm:px-4 py-6 sm:py-8 max-w-4xl">
                    <Card className="backdrop-blur-md bg-background/95 border-border/20 shadow-xl">
                        <CardHeader className="text-center pb-6 sm:pb-8">
                            <div className="mx-auto w-12 h-12 sm:w-16 sm:h-16 bg-primary/10 rounded-full flex items-center justify-center mb-3 sm:mb-4">
                                <FileText className="w-6 h-6 sm:w-8 sm:h-8 text-primary" />
                            </div>
                            <CardTitle className="text-2xl sm:text-3xl font-bold bg-gradient-to-r from-foreground to-foreground/80 bg-clip-text text-transparent">
                                Terms of Service
                            </CardTitle>
                            <p className="text-foreground-muted mt-2 text-sm sm:text-base">
                                Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
                            </p>
                        </CardHeader>

                        <CardContent className="space-y-6 sm:space-y-8">
                            <div className="prose prose-gray max-w-none">
                                {/* Effective Date */}
                                <div className="p-4 bg-primary/5 rounded-lg border border-primary/20 mb-6">
                                    <p className="text-sm text-foreground-muted">
                                        <strong>Effective Date:</strong> 5th July 2025
                                    </p>
                                </div>

                                {/* Introduction */}
                                <section>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            This document is an electronic record under the Information Technology Act, 2000 and the applicable rules, including amendments. It is generated by a computer system and does not require any physical or digital signatures.
                                        </p>
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, requiring the publication of rules, regulations, privacy policy, and terms of use for access to or use of the domain name www.cinesaga.in ("Website"), including its mobile site and mobile application (collectively referred to as the "Platform").
                                        </p>
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            CINESAGA. Managed by Sagnik Films. Address - Kolkata (referred to as "Cinesaga", "we", "our", or "us").
                                        </p>
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            By accessing or using our Platform or services, you agree to be legally bound by these Terms and Conditions ("Terms"). Please read them carefully before using our services.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 1. Eligibility */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4 flex items-center">
                                        <Scale className="w-5 h-5 sm:w-6 sm:h-6 mr-2 text-primary" />
                                        1. Eligibility
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            By using the Platform, you confirm that you are at least 18 years of age or are accessing the Platform under the supervision of a parent or legal guardian.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 2. User Account and Information */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4 flex items-center">
                                        <Users className="w-5 h-5 sm:w-6 sm:h-6 mr-2 text-primary" />
                                        2. User Account and Information
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            You agree to provide accurate, complete, and updated registration information.
                                        </p>
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            You are responsible for maintaining the confidentiality of your login credentials and for all activities under your account.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 3. Services Offered */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4 flex items-center">
                                        <Globe className="w-5 h-5 sm:w-6 sm:h-6 mr-2 text-primary" />
                                        3. Services Offered
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            Cinesaga offers digital streaming services including movies, series, and other multimedia content via subscriptions. Availability of content may vary based on licensing and geographic restrictions.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 4. Payment and Billing */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4 flex items-center">
                                        <CreditCard className="w-5 h-5 sm:w-6 sm:h-6 mr-2 text-primary" />
                                        4. Payment and Billing
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            All fees for subscriptions or services are listed on the Platform and are subject to change without notice.
                                        </p>
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            Payments once made are non-refundable unless otherwise explicitly stated in our Refund & Cancellation Policy.
                                        </p>
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            By subscribing, you authorize us to charge the applicable fees to your selected payment method.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 5. Intellectual Property */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4 flex items-center">
                                        <Shield className="w-5 h-5 sm:w-6 sm:h-6 mr-2 text-primary" />
                                        5. Intellectual Property
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            All content on the Platform—including videos, graphics, text, design, and logos—is the intellectual property of Cinesaga or its licensors.
                                        </p>
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            You may not reproduce, modify, distribute, or publicly display any content without our prior written consent.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 6. Restrictions on Use */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4 flex items-center">
                                        <AlertTriangle className="w-5 h-5 sm:w-6 sm:h-6 mr-2 text-primary" />
                                        6. Restrictions on Use
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            You agree:
                                        </p>
                                        <ul className="list-disc list-inside space-y-2 text-foreground-muted ml-4">
                                            <li>Not to copy, share, or distribute any content without authorization.</li>
                                            <li>Not to reverse engineer or tamper with the Platform.</li>
                                            <li>Not to use the Platform for unlawful, harmful, or exploitative purposes.</li>
                                        </ul>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 7. Third-Party Links */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4">
                                        7. Third-Party Links
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            The Platform may contain links to third-party websites. We do not control or endorse these sites, and we are not responsible for their content or terms of use.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 8. Termination or Suspension */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4">
                                        8. Termination or Suspension
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            We reserve the right to terminate or suspend your access without notice if we believe you are in violation of these Terms, applicable laws, or if required by any enforcement or regulatory authority.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 9. Limitation of Liability */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4">
                                        9. Limitation of Liability
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            In no event shall Cinesaga be liable for any indirect, incidental, special, or consequential damages, including loss of profits, data, or business opportunities. Our liability shall not exceed ₹100 or the subscription amount paid by you, whichever is lower.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 10. Indemnity */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4">
                                        10. Indemnity
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            You agree to indemnify and hold harmless Cinesaga, its directors, employees, and affiliates from any claims, damages, or losses arising out of your use of the Platform, your violation of these Terms, or your infringement of any third-party rights.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 11. Force Majeure */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4">
                                        11. Force Majeure
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            We shall not be liable for failure to perform our obligations if such failure is due to circumstances beyond our reasonable control, including natural disasters, internet failures, governmental actions, or legal restrictions.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 12. Governing Law and Jurisdiction */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4">
                                        12. Governing Law and Jurisdiction
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            These Terms are governed by the laws of Jurisdiction of Kolkata Only.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 13. Changes to Terms */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4">
                                        13. Changes to Terms
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            We may modify these Terms at any time. It is your responsibility to review them periodically. Continued use of the Platform constitutes your acceptance of the revised Terms.
                                        </p>
                                    </div>
                                </section>

                                <Separator className="my-8" />

                                {/* 14. Contact Us */}
                                <section>
                                    <h2 className="text-xl sm:text-2xl font-semibold mb-3 sm:mb-4">
                                        14. Contact Us
                                    </h2>
                                    <div className="space-y-4">
                                        <p className="text-foreground-muted leading-relaxed text-sm sm:text-base">
                                            For any questions or concerns regarding these Terms, you may contact us at:
                                        </p>
                                        <div className="grid md:grid-cols-2 gap-6">
                                            <div className="space-y-3">
                                                <div className="flex items-center space-x-3">
                                                    <span className="text-foreground-muted">📧 Email:</span>
                                                    <span className="text-foreground">info.cinesaga@gmail.com</span>
                                                </div>
                                                <div className="flex items-center space-x-3">
                                                    <span className="text-foreground-muted">📞 Phone:</span>
                                                    <span className="text-foreground">+91 82829 79209</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </section>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default TermsOfService;
